import { Inter } from "next/font/google";
import Head from "next/head";
import Navbar from "@/components/navbar";
import Main from "@/components/main";
import About from "@/components/about";
import Skills from "@/components/skills";
import Projects from "@/components/projects";
import Contact from "@/components/contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio - Nuttpon Yumin</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      <Navbar />
      <Main />
      <About />
      <Projects />
      <Skills />
      <Contact />
    </div>
  );
}
